config/routes.rb
Rails.application.routes.draw do

  root "todos#index"

  get "/todos", to: "todos#index", as:"todos" #<--- best preactice

  post "/todos", to: "todos#create"

  delete "/todos/:task", to: "todos#delete", as: "todo"

  delete "/todos", to: "todos#delete_all"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = session[:todos] ||=[]
  end
  def create
    form_data = params[:task]
    @todos = session[:todos]
    @todos << form_data
    redirect_to todos_path

  end
  def delete
    todos = session[:todos]
    todos.delete(params[:task])
      redirect_to todos_path
  end

  def delete_all
    todos = session[:todos]
    todos.clear
    redirect_to todos_path

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_helper.rb
module TodoHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/index.html.erb
<h1>Todos#index</h1>
   <%= form_tag(todos_path) do %>
     <p>
      <%= label_tag(:task) %>
      <%= text_field_tag(:task, nil, autofocus: true) %>
    </p>
     <%= submit_tag "Add"%>
  <% end %>

  <% @todos.each do |todo| %>
  <p> <%=todo%></p> <%= link_to "X", todo_path(todo), method: "delete" %>
  <% end %>

  <%= button_to "Delete", todos_path, :method => :delete %>